---
title: "Swiss"
author: "Michael Kahle"
date: "31 1 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Swiss Homogeneus Rows



https://www.meteoschweiz.admin.ch/home/klima/schweizer-klima-im-detail/homogene-messreihen-ab-1864.html?region=Tabelle

```{r cars}

locations <- c('BAS','BER','CHM','CHD','GSB','DAV','ENG','GVE','LUG','PAY','SIA','SIO','SAE','SMA')
for (station in locations) {
   print(paste("Reading station:", station))
   fileSt <- paste("csv/monthly_tp_", station, ".csv", sep="")
   url <- paste("https://www.meteoschweiz.admin.ch/product/output/climate-data/homogenous-monthly-data-processing/data/homog_mo_", station, ".txt", sep="")
  homoData <- read.csv(url, sep="", na = "NA", skip = 27)
  
 write.table(homoData, file = fileSt, append = FALSE, quote = TRUE, sep = ",",
            eol = "\n", na = "NA", dec = ".", row.names = FALSE,
            col.names = TRUE, qmethod = "escape", fileEncoding = "UTF-8")  
  
}







```

